package com.aib;
import com.aib.*
dialect "mvel"
import java.util.*
import com.aib.enums.*

rule "checkAutoTransact" salience 100
    when
        sp:StockProfile()
    // check if the transaction hasn't expiread
        at:AutoTransaction(stockProfile == sp
            && at.getWaitUntil().compareTo(Calendar.getInstance()) >= 0
            && transactionType == TransactionType.BUY
            && thresholdPrice >= sp.currentPrice)
//        check that the transaction actually  belongs to an investor
//        + check if the investor has enough available funds
        i:Investor(autoTransactionSet.contains(at) && availableFunds >= (at.noOfShares * sp.currentPrice))
//        i:Investor(autoTransactionSet != null && !autoTransactionSet.isEmpty)
    then
        // we execute transaction
        Investor.executeTransaction(i, at);
        System.out.println("Transaction for buying stocks for " + i.name + " has been successfully executed");

end





//rule "discount for new customers" salience -2
//when
//	c:Client(type=="New")
//	o:Order(client==c)
//	a:Article(order==o)
//	p:Product(a.product==p)
//then
//	o.setDiscount(0.1);
//	System.out.println("the discount for a new Customer is "+o.getDiscount());
//	System.out.println(o.getOrderValue());
//end
//
//rule "discount for new customers that buy luxury products" salience 4
//when
//	c:Client(type=="New")
//	o:Order(client==c)
//	a:Article(order==o)
//	p:Product(type=="Medicine", a.product==p)
//then
//	o.setDiscount(0.05);
//	System.out.println("the discount for luxury "+o.getDiscount());
//	System.out.println(o.getOrderValue());
//end
//
//
//rule "discount for medicines sold to new customers"
//when
//	c:Client(type=="New")
//	o:Order(client==c)
//	a:Article(order==o)
//	p:Product(type=="Medicine", a.product==p)
//then
//	o.setDiscount(0.0);
//	System.out.println("The product that has the name "+p.getName()+" has the discount equal to "+p.getDiscount());
//end
//
//rule "discount for new customers which by grocery products"
//when
//	c:Client(type=="New")
//	o:Order(client==c)
//	a:ArticleOfOrder(order==o)
//	p:Product(type=="Grocery", a.product==p)
//then
//	p.setDiscount(0.1);
//	System.out.println("The product that has the name "+p.getName()+" has the discount equal to "+p.getDiscount());
//end
